apiVersion: v1
kind: Service
metadata:
  name: travel-community-service
spec:
  selector:
    app: travel-community
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

